#!/bin/bash

set -e

# James Dingwall
# Setup the dmuk repository

apt-key add - < repo-dmuk.key

cat << EOF > /etc/apt/sources.list.d/dmuk.list
deb http://localhost/ubuntu $(lsb_release -sc) main
deb-src http://localhost/ubuntu $(lsb_release -sc) main
EOF

apt-get update
