#!/bin/bash

set -e

# James Dingwall
# DMUK

if /usr/bin/which diff ; then
    for i in group gshadow passwd shadow ; do
        if ! diff -u  "/etc/${i}" "start-${i}" ; then
            cat << EOF
#     #                                                   ###
#  #  #    ##    #####   #    #     #    #    #   ####    ###
#  #  #   #  #   #    #  ##   #     #    ##   #  #    #   ###
#  #  #  #    #  #    #  # #  #     #    # #  #  #         #
#  #  #  ######  #####   #  # #     #    #  # #  #  ###
#  #  #  #    #  #   #   #   ##     #    #   ##  #    #   ###
 ## ##   #    #  #    #  #    #     #    #    #   ####    ###

${i} content changed during this build phase
EOF
            sleep 10
        fi
    done
fi

# Try python again if it didn't run before
if [ -f NOPYTHON ] && /usr/bin/which python3 ; then
    # Prefer our python version if available
    /usr/bin/env python3 uidgid.py
fi

# Cleanup odd password bits
if [ -d /home/syslog ] ; then
    rmdir /home/syslog
fi
